### ISSUE TITLE
Import stuck on importing users

### ISSUE THREAD

**Issue by rsramek** [bdharrington7/nodebb-plugin-import-vanilla#12]
I am trying to import vanilla into notebb, the import successfully imports categories/subforums
but gets stuck at: 

[2016-04-28T10:38:25.212Z] current phase: usersImportStart (time since previous phase: 0s)
(Does not progress, status is idle, no users have been added.)

I'd look into more detailed logs but I have no idea where I can find them.
Nodebb: v1.0.0
nodebb-plugin-import at head, nodebb-plugin-import-vanilla at head.
(assuming here npm install xxx installs latest from git).

Do you have any ideas? Thanks!

**Comment by rsramek** [comment]
Found the error logs:

importer.phase { phase: 'categoriesImportStart',
  data: undefined,
  timestamp: 1461850262728 }
importer.progress { count: 0, total: 1, percentage: 0 }
importer.success [2016-04-28T13:31:02.751Z] Importing 3 categories.

[nodebb-plugin-import] importer.success [2016-04-28T13:31:02.751Z] Importing 3 categories.
importer.progress { count: 1, total: 3, percentage: 33.33333333333333 }
importer.progress { count: 2, total: 3, percentage: 66.66666666666666 }
importer.progress { count: 3, total: 3, percentage: 100 }
importer.success [2016-04-28T13:31:02.846Z] Imported 3/3 categories

[nodebb-plugin-import] importer.success [2016-04-28T13:31:02.846Z] Imported 3/3 categories
importer.progress { count: 1, total: 1, percentage: 100 }
importer.success [2016-04-28T13:31:02.849Z] Phase ::: categoriesImportDone


[nodebb-plugin-import] importer.success [2016-04-28T13:31:02.849Z] Phase ::: categoriesImportDone

importer.phase { phase: 'categoriesImportDone',
  data: undefined,
  timestamp: 1461850262850 }
importer.success [2016-04-28T13:31:02.861Z] Phase ::: usersImportStart


[nodebb-plugin-import] importer.success [2016-04-28T13:31:02.861Z] Phase ::: usersImportStart

importer.phase { phase: 'usersImportStart',
  data: undefined,
  timestamp: 1461850262862 }
importer.progress { count: 0, total: 1, percentage: 0 }
28/4 09:31 [23706] - [31merror[39m: TypeError: Cannot read property 'lastIndexOf' of null
    at getActualProfilePath (/root/nodebb/node_modules/nodebb-plugin-import-vanilla/index.js:123:29)
    at /root/nodebb/node_modules/nodebb-plugin-import-vanilla/index.js:107:36


How can I configure a local version of the plug-in? I tried downloading it, modifying the code and typing npm ./nodebb-plugin-import-vanilla/
but that didn't seem to work.

**Comment by rsramek** [comment]
Nevermind, the issue is that _picture and _readTids are NULL in a fresh vanilla forum that has only been imported into. I fixed it but the code doesn't sanitize the values.

**Comment by bdharrington7** [comment]
Hi @rsramek glad you found the cause (make a PR if you know how to fix it please!) I never tested on a fresh install, so I never came across that scenario. 

It seems you might be a little confused about how npm works; it's just a package manager for nodejs packages to be published to, for convenience. It actually takes a separate step, so you might see outdated packages in npm compared to what's in the GitHub repo (the two are exclusive, by the way, code doesn't have to be in GitHub to be a published package in npm). 

To get the latest from a repository, you would have to `git clone` it into your node modules folder, and then `npm install` inside the repo's folder to install its dependencies

**Comment by bdharrington7** [comment]
Closing due to inactivity

**Comment by whuut** [comment]
@rsramek how did you fix it? I have the same issue.
